### PR TITLE
Fix users seed + chatbot overlaying video-call menu btn

### LINKED ISSUE #508: Chatbot is overlaying disconnect button in call

### LINKED ISSUE #542: Fix user seed
the seed currently creates users in firebase emulator but not firestore related data

### PR DESCRIPTION
**Pull request by MattiaPrimavera**
fix #508 , fix #542

### CODE REVIEW

**Review by HugoGresse — APPROVED** [review]

File: functions/src/api/utils/seeds/seedFirestore.ts [hunk 1]
```diff
@@ -1,18 +1,23 @@
 import { db } from '../../../firebase/firebase'
 import { COLLECTIONS } from '../../../db/constants'
-import { UID } from '../../../types/uid'
 import { GroupDao } from '../../../db/GroupDao'
+import { setNewUserData } from '../../v1/utils/UserUtils'
+
+export const seedFirestore = async (users: any) => {
+    const { premiumUser, freeUser, overQuotaUser } = users
+    await setNewUserData(premiumUser.id, premiumUser)
```
Comment (ntchou) [inline functions/src/api/utils/seeds/seedFirestore.ts:8]: maybe use a loop?

**Review by ntchou — APPROVED** [review]
