### PR TITLE
Set correct room password & join room fixes

### LINKED ISSUE #345: Set correct room password
- use the password when in the join url
- do not use any password in case the premium user wants to create a new room

### PR DESCRIPTION
**Pull request by MattiaPrimavera**
- Set correct room password (previously hard-coded) ->
workaround to handle the admin user navigating to `PremiumVideo` page: from the Dashboard we send him to `/premium-video/room/${roomId}?passcode=admin` since the passcode is required by the original code. When the passcode is `admin` although, it is not gonna be sent to `joinRoom` endpoint, so that a new password will be created on API side
- Hide sign out button for anonymous users
- retry `getJwtToken` (explained in code comment)
- move temporary login UI into a Modal window. Show the modal on login button click
- Add `LoginState` component that subscribes to auth state changes (otherwise the subscription won't occur, since `Login` component is now within a Modal window)
- pave the way to remove `EmulatorLogin` -> emulator login helper buttons moved into `LoginModal`
- handle join room error: "Token must be a string" was displayed
- send `participantName` to `joinRoom` endpoint

Fix #345

### CODE REVIEW

File: src/actions/getJwtToken.ts [hunk 1]
```diff
@@ -2,12 +2,47 @@ import { functions } from '../firebase/firebase'
...
+    while (retriesNumber <= maxRetries) {
+        try {
+            const result = await promise
+            return result
+        } catch (err) {
+            retriesNumber++
+            await new Promise((resolve) => {
+                setTimeout(function () {
+                    resolve(true)
+                }, retryInterval)
```
Comment (HugoGresse) [inline src/actions/getJwtToken.ts:21]: We need to increase the delay, maybe more something like this: 
```
setTimeout(, retriesNumber^1.3)
```

File: src/actions/getJwtToken.ts [hunk 2]
```diff
@@ -2,12 +2,47 @@ import { functions } from '../firebase/firebase'
...
+async function tryAtMost(promise, maxRetries, retryInterval) {
+    let retriesNumber = 0
+    while (retriesNumber <= maxRetries) {
+        try {
+            const result = await promise
+            return result
+        } catch (err) {
+            retriesNumber++
+            await new Promise((resolve) => {
+                setTimeout(function () {
```
Comment (HugoGresse) [inline src/actions/getJwtToken.ts:19]: can move to 
```

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
```

File: src/actions/getJwtToken.ts [hunk 3]
```diff
@@ -2,12 +2,47 @@ import { functions } from '../firebase/firebase'
...
+
 export const getJwtToken = async (uid: UID): Promise<JWTToken> => {
     try {
-        const result = await functions.getToken({
+        const getTokenPromise = functions.getToken({
             uid,
         })
 
+        /*
+            tryAtMost is needed because before a token can exist, firebase functions hook
```
Comment (HugoGresse) [inline src/actions/getJwtToken.ts:36]: `firebase functions hook` > `Firebase user create trigger need to successfully...` is more precise

File: src/components/App/LoginState/LoginState.tsx [hunk 4]
```diff
@@ -0,0 +1,21 @@
+import React, { useEffect } from 'react'
+import { authInstance } from '../../../firebase/firebase'
+import { didSignin } from '../../../actions/userActions'
+import { useDispatch } from 'react-redux'
+import { hideLoginModal } from '../../LoginModal/loginModalActions'
+
+const LoginState = () => {
```
Comment (HugoGresse) [inline src/components/App/LoginState/LoginState.tsx:7]:
```suggestion
const AuthStateChangedListener = () => {
```

File: src/components/LoginModal/loginModalReducer.ts [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+        switch (type) {
+            case HIDE_LOGIN_MODAL:
+                return {
+                    ...draft,
+                    isDisplayed: false,
+                }
+            case SHOW_LOGIN_MODAL:
+                return {
+                    ...draft,
+                    isDisplayed: true,
```
Comment (HugoGresse) [inline src/components/LoginModal/loginModalReducer.ts:20]: if you only mutate one field, you can do draft.isDisplayed directly. 
This where needed for destructuring the whole object in draft, which is not supported by immer.

File: src/pages/Admin/Dashboard.tsx [hunk 6]
```diff
@@ -16,10 +18,19 @@ const InformationBlock = styled.div`
 
 export default function Dashboard() {
     const { t } = useTranslation('admin')
+    const history = useHistory()
+    const startPremiumVideoCall = () => {
+        history.push('/premium-video/room/testRoom?passcode=admin')
```
Comment (HugoGresse) [inline src/pages/Admin/Dashboard.tsx:23]: this will not last long, only the first admin will be able to use it, testRoom (roomId) will be already used after.

File: src/pages/PremiumVideoCall/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx [hunk 7]
```diff
@@ -93,12 +92,20 @@ export default function DeviceSelectionScreen({
...
     const handleJoin = async () => {
         setIsLoading(true)
-        const api = new Api(token)
-        const { jwtAccessToken } = await api.joinRoom(roomId, 'test-password') // TODO pass the password variable
-        dispatch(actions.setRoomId(roomId))
-        dispatch(actions.setHostName(name))
-        connect(jwtAccessToken, roomId)
-        setIsLoading(false)
+        try {
+            const twilioVideoToken = await getTwilioVideoToken(
```
Comment (HugoGresse) [inline src/pages/PremiumVideoCall/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx:96]: this could probably be within an action, and dispatch the roomid and hostName within the action.

File: src/services/api.ts [hunk 8]
```diff
@@ -19,9 +19,20 @@ export class Api {
...
-        return this.post(`/rooms/${roomId}/join`, { password })
+        try {
+            const joinResponse = await this.post(`/rooms/${roomId}/join`, {
+                participantName,
+                password,
+            })
+            return joinResponse
+        } catch (err) {
+            throw new Error(
+                'Connection error, maybe the room has not been created yet. Pls try again later'
```
Comment (HugoGresse) [inline src/services/api.ts:33]: use API error message there.

File: src/services/api.ts [hunk 9]
```diff
@@ -44,6 +55,10 @@ export class Api {
             },
             body: data ? JSON.stringify(data) : null,
         })
+
+        if (response.status !== 200 && response.status !== 204) {
```
Comment (HugoGresse) [inline src/services/api.ts:59]: I believe fetch will throw if received error. We can also used `response.ok`,  all http error code >= 200, < 400 are considered valid (FYI)

File: src/actions/getJwtToken.ts (hunk 1 above)
Comment (MattiaPrimavera) [reply src/actions/getJwtToken.ts:21]: why ? Isn't retry with increased delay a retry practice not to make lots of calls, in case a service may be down or can't answer ? In our case we only need the hook to have been executed

File: src/pages/Admin/Dashboard.tsx (hunk 6 above)
Comment (MattiaPrimavera) [reply src/pages/Admin/Dashboard.tsx:23]: exactly, this will be fixed with the real room name/id. For the moment it only allows to test a "UI flow" instead of manually changing or pasting the url

File: src/services/api.ts (hunk 8 above)
Comment (MattiaPrimavera) [reply src/services/api.ts:33]: It was *Payment required*, should I use that, so that we'll change the text on the API side if needed ?

File: src/services/api.ts (hunk 9 above)
Comment (MattiaPrimavera) [reply src/services/api.ts:59]: I could print the error result, so I guess it does not throw an error, I also created #393 for this reason. If you agree with #393, this code will be replaced anyway

File: src/pages/PremiumVideoCall/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx (hunk 7 above)
Comment (MattiaPrimavera) [reply src/pages/PremiumVideoCall/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx:96]: How would you call the function to make that clear that it
- gets a video token
- dispatches the hostName
- dispatches the roomName

File: src/actions/getJwtToken.ts (hunk 1 above)
Comment (HugoGresse) [reply src/actions/getJwtToken.ts]: yes, the trigger may be cold (because it's a serverless) and the first time can take up to 2 or 3s (hot is aready used within last 10min =  much shorter delay). It's a common practice within mobile apps to increase the retry delay. + I don't know the exact delay of the login trigger.

File: src/services/api.ts (hunk 8 above)
Comment (HugoGresse) [reply src/services/api.ts]: I believe we can do that for the time being and check later on for the transation.

File: src/pages/PremiumVideoCall/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx (hunk 7 above)
Comment (HugoGresse) [reply src/pages/PremiumVideoCall/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx:96]: initVideoToken
loadTwilioRoomInfo

we don't need to know what will dispatch the action, just what it's doing overall.

File: src/services/api.ts (hunk 8 above)
Comment (MattiaPrimavera) [reply src/services/api.ts]: I replaced as asked

File: src/pages/PremiumVideoCall/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx (hunk 7 above)
Comment (MattiaPrimavera) [reply src/pages/PremiumVideoCall/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx:96]: I think a nice approach could be to create a `connectToRoom` async action, that is dispatched once clicking on `Join`. This action would:
- dispatch the `hostName` & `roomId`
- take care of showing/hiding the loader

We'd thus need to move the loader indicator to redux. I'd treat this in a separate low priority PR although (cleaner code)

File: src/actions/getJwtToken.ts [hunk 10]
```diff
@@ -2,12 +2,51 @@ import { functions } from '../firebase/firebase'
...
+
+async function tryAtMost(promise, maxRetries, retryInterval) {
+    let retriesNumber = 0
+    while (retriesNumber <= maxRetries) {
+        try {
+            retriesNumber++
+            const result = await promise
+            return result
+        } catch (err) {
+            await sleep(RETRY.interval + RETRY.number * 1.3)
```
Comment (HugoGresse) [inline src/actions/getJwtToken.ts:26]: in the last comment i used `^` rahter than multiply, which grealty increase the duration on retry

File: src/components/App/AuthStateChangedListener/AuthStateChangedListener.tsx [hunk 11]
```diff
@@ -0,0 +1,20 @@
...
+import { authInstance } from '../../../firebase/firebase'
+import { didSignin } from '../../../actions/userActions'
+import { useDispatch } from 'react-redux'
+import { hideLoginModal } from '../../LoginModal/loginModalActions'
+
+const AuthStateChangedListener = () => {
+    const dispatch = useDispatch()
+
+    useEffect(() => {
+        return authInstance.onAuthStateChanged((user) => {
```
Comment (HugoGresse) [inline src/components/App/AuthStateChangedListener/AuthStateChangedListener.tsx:11]: nice

File: src/pages/PremiumVideoCall/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx (hunk 7 above)
Comment (HugoGresse) [reply src/pages/PremiumVideoCall/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx:96]: ok

**Review by HugoGresse — CHANGES_REQUESTED** [review]

File: src/components/LoginModal/LoginModal.tsx [hunk 12]
```diff
@@ -0,0 +1,66 @@
...
+            )
+            console.log('Signed In with user: ', user)
+        } catch (error) {
+            const { code, message } = error
+            console.log(`Error email auth: ${code}, message: ${message}`)
+        }
+    }
+
+    return (
+        <>
```
Comment (ntchou) [inline src/components/LoginModal/LoginModal.tsx:34]: Fragment is not necessary

File: src/components/LoginModal/LoginModal.tsx [hunk 13]
```diff
@@ -0,0 +1,66 @@
...
+                        <Button
+                            onClick={() =>
+                                signInWithEmailAndPassword(overQuotaUser)
+                            }>
+                            OverQuota
+                        </Button>
+                    </>
+                )}
+            </Modal>
+        </>
```
Comment (ntchou) [inline src/components/LoginModal/LoginModal.tsx:64]: fragment is not necessary

File: src/pages/PremiumVideoCall/state/usePasscodeAuth/usePasscodeAuth.ts [hunk 14]
```diff
@@ -87,7 +109,9 @@ export default function usePasscodeAuth() {
                         history.replace(window.location.pathname)
                     }
                 })
-                .then(() => setIsAuthReady(true))
```
Comment (ntchou) [inline src/pages/PremiumVideoCall/state/usePasscodeAuth/usePasscodeAuth.ts:90]: async/await ?

File: src/components/App/AuthStateChangedListener/AuthStateChangedListener.tsx [hunk 15]
```diff
@@ -0,0 +1,20 @@
+import React, { useEffect } from 'react'
+import { authInstance } from '../../../firebase/firebase'
+import { didSignin } from '../../../actions/userActions'
+import { useDispatch } from 'react-redux'
+import { hideLoginModal } from '../../LoginModal/loginModalActions'
+
+const AuthStateChangedListener = () => {
```
Comment (ntchou) [inline src/components/App/AuthStateChangedListener/AuthStateChangedListener.tsx:7]: maybe create a hook `useAuthStateChangedListener` instead a react component ?

File: src/pages/Admin/Dashboard.tsx [hunk 16]
```diff
@@ -16,10 +18,19 @@ const InformationBlock = styled.div`
...
+    }
 
     return (
         <IonContent style={{ '--background': 'white' }}>
-            <InformationBlock>{t('dashboard.welcome')}</InformationBlock>
+            <InformationBlock>
+                {t('dashboard.welcome')}
+                <Button onClick={() => startPremiumVideoCall()}>
```
[the remark this answers is not in the document]
Comment (MattiaPrimavera) [reply src/pages/Admin/Dashboard.tsx:30]: nice suggested change, I'll use in the future. Concerning this specific change, this code will be replaced once integrating the real `DashBoard` page

File: src/pages/Admin/Dashboard.tsx [hunk 17]
```diff
@@ -16,10 +18,19 @@ const InformationBlock = styled.div`
...
+                    Start Call
```
[the remark this answers is not in the document]
Comment (MattiaPrimavera) [reply src/pages/Admin/Dashboard.tsx:31]: This code will be replaced

File: src/components/LoginModal/LoginModal.tsx [hunk 18]
```diff
@@ -0,0 +1,66 @@
...
+                    dispatch(hideLoginModal())
+                }}>
+                <Login />
+                {isAuthEmulatorEnabled() && (
+                    <>
+                        <Button
+                            onClick={() =>
+                                signInWithEmailAndPassword(paidUser)
+                            }>
+                            Paid
```
[the remark this answers is not in the document]
Comment (MattiaPrimavera) [reply src/components/LoginModal/LoginModal.tsx:47]: These buttons are used to simulate login when using firebase emulator suite locally. No need for translations

File: src/components/LoginModal/LoginModal.tsx (hunk 12 above)
Comment (MattiaPrimavera) [reply src/components/LoginModal/LoginModal.tsx:34]: What can I return, considering `LoginModal` is a component ?

File: src/pages/PremiumVideoCall/state/usePasscodeAuth/usePasscodeAuth.ts (hunk 14 above)
Comment (MattiaPrimavera) [reply src/pages/PremiumVideoCall/state/usePasscodeAuth/usePasscodeAuth.ts:90]: this code is from the original [Twilio Video App project](https://github.com/twilio/twilio-video-app-react). I think we'll have to state in the future if to update all that code in order to meet our code styling guidelines

File: src/components/App/AuthStateChangedListener/AuthStateChangedListener.tsx (hunk 15 above)
Comment (MattiaPrimavera) [reply src/components/App/AuthStateChangedListener/AuthStateChangedListener.tsx:7]: #409

File: src/components/LoginModal/LoginModal.tsx (hunk 12 above)
Comment (ntchou) [reply src/components/LoginModal/LoginModal.tsx:34]: Return directly

 ````
return (<Modal>


</Modal>)

````

File: src/components/LoginModal/LoginModal.tsx (hunk 18 above)
[the remark this answers is not in the document]
Comment (ntchou) [reply src/components/LoginModal/LoginModal.tsx:47]: Ok

File: src/pages/PremiumVideoCall/state/usePasscodeAuth/usePasscodeAuth.ts (hunk 14 above)
Comment (ntchou) [reply src/pages/PremiumVideoCall/state/usePasscodeAuth/usePasscodeAuth.ts:90]: Ok

File: src/pages/Admin/Dashboard.tsx (hunk 17 above)
[the remark this answers is not in the document]
Comment (ntchou) [reply src/pages/Admin/Dashboard.tsx:31]: Ok

**Review by ntchou — APPROVED** [review]
