### PR TITLE
Crashlytics + Update npm scripts

### LINKED ISSUE #541: Set local environment scripts
- use `.env.development` file for local environment
- add `.env.staging` for staging
- `npm start` uses local environment
- `npm start:staging` uses staging environment

### LINKED ISSUE #558: Use Crashlytics for crash reports

### PR DESCRIPTION
**Pull request by MattiaPrimavera**
- Use Crashlytics : fix #558
- Set local environments scripts: fix #541
- use dev project when running emulator locally
- automatically seed emulators after they are started
- use `.env.development` for local development (start && run:${platform} commands)
- use `.env.staging` for staging server builds (start:staging && run:${platform}:staging, build:staging)
- upgrade to firebaseMessagingVersion =  '20.1.6' to fix build failure

### CODE REVIEW

File: src/pages/AdminDashboard/CreateRoomForm/formValidation.tsx [hunk 1]
```diff
@@ -10,8 +10,10 @@ export const validationSchema = Yup.object().shape({
         .test('startAt', i18n.t('invalid-date'), (value) => {
             //use custom format instead timestamp and isPast (date-fns). It could be have small difference between datepicker date (seconds) and now
             const dateFormat = 'yyyy-mm-ddhh:mm'
-            const isValid =
-                format(value, dateFormat) >= format(new Date(), dateFormat)
+            console.log('Value: ', value)
```
Comment (HugoGresse) [inline src/pages/AdminDashboard/CreateRoomForm/formValidation.tsx:13]:
```suggestion
```

**Review by HugoGresse — APPROVED** [review]

File: README.md [hunk 2]
```diff
@@ -29,27 +34,42 @@ npm i # Install dependencies
...
+npm run:android
 ```
 
 ### Seed local database
 
+**Note**: database is automatically seed when using emulators locally
+
 To seed/populate the emulator database with test users and some basic firestore data, you can use a route on the API. 
-1. Start the API using emulators: `cd function && npm run serve-emulators`
+1. Start the API using emulators: `cd function && npm run serve-watch`
```
Comment (MattiaPrimavera) [inline README.md:72]:
```suggestion
1. Start the API using emulators: `cd function && npm run serve:watch`
```

**Review by HugoGresse — APPROVED** [review]
